Test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,25 +1,33 @@
 version: 2.1
 
+orbs:
+  win: circleci/windows@2.2.0
+
+references:
+  paths:
+    test-results: &TEST_RESULTS /tmp/test-results
+    win-test-results: &WIN_TEST_RESULTS c:\Users\circleci\AppData\Local\Temp\test-results
+    win-go-dir: &WIN_WORKING_DIR c:\gopath\src\github.com\hashicorp\go-getter
+    win-gomod-dir: &WIN_GOMOD_DIR c:\Windows\system32\config\systemprofile\go\pkg\mod
+  environment: &ENVIRONMENT
+    GOMAXPROCS: 4
+    GO111MODULE: "on"
+    GOPROXY: https://proxy.golang.org/
+    TEST_RESULTS_DIR: &TEST_RESULTS_DIR /tmp/test-results/hcl
+    WIN_TEST_RESULTS: *WIN_TEST_RESULTS
+    WIN_WORKING_DIR: *WIN_WORKING_DIR
+    WIN_GOMOD_DIR: *WIN_GOMOD_DIR
+
 executors:
   go:
     docker:
       - image: circleci/golang:1.14
-    environment:
-      GOMAXPROCS: 4
-      GO111MODULE: "on"
-      GOPROXY: https://proxy.golang.org/
-      TEST_RESULTS_DIR: &TEST_RESULTS_DIR /tmp/test-results
 
-jobs:
-  go-checks:
-    executor:
-      name: go
+commands:
+  git-verify:
     steps:
-      - checkout
-      - run: go mod verify
-      - run: make fmt
-      - run:
-          name: verify no code was generated
+      - run: 
+          name: "Verify no code was generated"
           command: |
             if [[ -z $(git status --porcelain) ]]; then
               echo "Git directory is clean."
@@ -28,6 +36,18 @@ jobs:
               git status --porcelain
               exit 1
             fi
+
+jobs:
+  go-checks:
+    executor:
+      name: go
+    environment: 
+      <<: *ENVIRONMENT
+    steps:
+      - checkout
+      - run: go mod verify
+      - run: make fmt
+      - git-verify
 
   go-test:
     executor:
@@ -43,19 +63,95 @@ jobs:
             PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
             echo "Running $(echo $PACKAGE_NAMES | wc -w) packages"
             echo $PACKAGE_NAMES
-            gotestsum --format=short-verbose --junitfile $TEST_RESULTS_DIR/gotestsum-report.xml -- -p 2 -cover -coverprofile=cov_$CIRCLE_NODE_INDEX.part $PACKAGE_NAMES
+            gotestsum --format=short-verbose --junitfile $TEST_RESULTS_DIR/gotestsum-report.xml -- -p 2 -cover -coverprofile=linux_cov_$CIRCLE_NODE_INDEX.part $PACKAGE_NAMES
 
       # save coverage report parts
       - persist_to_workspace:
           root: .
           paths:
-            - cov_*.part
+            - linux_cov_*.part
 
       - store_test_results:
           path: *TEST_RESULTS_DIR
       - store_artifacts:
           path: *TEST_RESULTS_DIR
 
+  win-tests:
+    executor: 
+      name: win/default
+      shell: bash --login -eo pipefail
+    environment:
+      <<: *ENVIRONMENT
+    working_directory: *WIN_WORKING_DIR
+    parameters:
+      go-version:
+        type: string
+      gotestsum-version:
+        type: string
+    steps: 
+      - run: git config --global core.autocrlf false
+      - checkout
+      - attach_workspace:
+          at: .
+      - git-verify
+      - run: 
+          name: Setup (remove pre-installed go)
+          command: |
+            rm -rf "c:\Go"
+            mkdir -p $TEST_RESULTS_DIR
+
+      - restore_cache:
+          keys:
+            - windows-golang-<< parameters.go-version >>-cache
+            - windows-gomod-cache-{{ checksum "go.mod" }}
+
+      - run: 
+          name: Install go version << parameters.go-version >>
+          command: | 
+            if [ ! -d "c:\go" ]; then
+              echo "Cache not found, installing new version of go"
+              curl --fail --location https://dl.google.com/go/go<< parameters.go-version >>.windows-amd64.zip --output go.zip
+              unzip go.zip -d "/c"
+            fi
+
+      - run: 
+          command: go mod download
+
+      - save_cache:
+          key: windows-golang-<< parameters.go-version >>-cache
+          paths:
+            - /go
+
+      - save_cache:
+          key: windows-gomod-cache-{{ checksum "go.mod" }}
+          paths:
+            - *WIN_GOMOD_DIR
+
+      - run:
+          name: Install gotestsum
+          command: |
+            curl --fail --location https://github.com/gotestyourself/gotestsum/releases/download/v<< parameters.gotestsum-version >>/gotestsum_<< parameters.gotestsum-version >>_windows_amd64.tar.gz --output gotestsum.tar.gz
+            tar -xvzf gotestsum.tar.gz
+
+      - run:
+          name: Run go tests
+          command: |
+            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
+            echo "Running $(echo $PACKAGE_NAMES | wc -w) packages"
+            echo $PACKAGE_NAMES
+            ./gotestsum.exe --format=short-verbose --junitfile $TEST_RESULTS_DIR/gotestsum-report.xml -- -p 2 -cover -coverprofile=win_cov_$CIRCLE_NODE_INDEX.part $PACKAGE_NAMES
+      
+      # save coverage report parts
+      - persist_to_workspace:
+          root: .
+          paths:
+            - win_cov_*.part
+
+      - store_test_results:
+          path: *WIN_TEST_RESULTS
+      - store_artifacts:
+          path: *WIN_TEST_RESULTS
+          
 workflows:
   version: 2
   test:
